/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telehealth;

import com.telehealth.Business.DB4OUtil.DB4OUtil;
import com.telehealth.Business.EcoSystem;
import com.telehealth.Business.Enterprise.Enterprise;
import com.telehealth.Business.Network.Network;
import com.telehealth.Business.Organization.Organization;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.telehealth.Business.Organization.Organization.Type;
import static telehealth.TeleHealthApp.logger;

/**
 *
 * @author RASHMI
 */
public class EnterprisePanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterprisePanel
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    Enterprise enterprise;
    Enterprise viewEnterprise;
    Network viewNetwork;
    Organization viewOrganization;
    
    @SuppressWarnings("empty-statement")
    public EnterprisePanel(TeleHealthView teleHealthView, EcoSystem system) {
        initComponents();
        this.system = system;
        ComboBoxEnterpriseType.setSelectedItem(null);
        networkJComboBox.setSelectedItem(null);
        cmbViewNetwork.setSelectedItem(null);
        cmbViewEnterprise.setSelectedItem(null);
        btnSubmit.setText("Submit");
        btnDelete.setVisible(false);
        populateTable();
        populateComboBox();
        populateViewComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtContactPerson = new javax.swing.JTextField();
        ComboBoxEnterpriseType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbViewNetwork = new javax.swing.JComboBox();
        cmbViewEnterprise = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(telehealth.TeleHealthApp.class).getContext().getResourceMap(EnterprisePanel.class);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtAddress1.setFont(resourceMap.getFont("txtAddress1.font")); // NOI18N
        txtAddress1.setName("txtAddress1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblEnterprise.setFont(resourceMap.getFont("tblEnterprise.font")); // NOI18N
        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address 1", "Address 2", "City", "State", "Zip", "Phone", "Email", "Contact Person", "Network"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEnterprise.setName("tblEnterprise"); // NOI18N
        tblEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnterpriseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);
        if (tblEnterprise.getColumnModel().getColumnCount() > 0) {
            tblEnterprise.getColumnModel().getColumn(0).setPreferredWidth(25);
            tblEnterprise.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title0")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title2")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title3")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title4")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title5")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title6")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title7")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title8")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(8).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title9")); // NOI18N
            tblEnterprise.getColumnModel().getColumn(9).setHeaderValue(resourceMap.getString("tblEnterprise.columnModel.title10")); // NOI18N
        }

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtAddress2.setFont(resourceMap.getFont("txtAddress2.font")); // NOI18N
        txtAddress2.setName("txtAddress2"); // NOI18N

        txtZip.setFont(resourceMap.getFont("txtZip.font")); // NOI18N
        txtZip.setName("txtZip"); // NOI18N

        txtName.setFont(resourceMap.getFont("txtName.font")); // NOI18N
        txtName.setName("txtName"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        txtEmail1.setFont(resourceMap.getFont("txtEmail1.font")); // NOI18N
        txtEmail1.setName("txtEmail1"); // NOI18N

        txtCity.setFont(resourceMap.getFont("txtCity.font")); // NOI18N
        txtCity.setName("txtCity"); // NOI18N

        txtPhone.setFont(resourceMap.getFont("txtPhone.font")); // NOI18N
        txtPhone.setName("txtPhone"); // NOI18N

        txtState.setFont(resourceMap.getFont("txtState.font")); // NOI18N
        txtState.setName("txtState"); // NOI18N

        txtContactPerson.setFont(resourceMap.getFont("txtContactPerson.font")); // NOI18N
        txtContactPerson.setName("txtContactPerson"); // NOI18N

        ComboBoxEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hospital", "Pharmacy ", "Insurance" }));
        ComboBoxEnterpriseType.setName("ComboBoxEnterpriseType"); // NOI18N

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        btnSubmit.setText(resourceMap.getString("btnSubmit.text")); // NOI18N
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.setName("networkJComboBox"); // NOI18N
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        btnDelete.setText(resourceMap.getString("btnDelete.text")); // NOI18N
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        cmbViewNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbViewNetwork.setName("cmbViewNetwork"); // NOI18N
        cmbViewNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViewNetworkActionPerformed(evt);
            }
        });

        cmbViewEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbViewEnterprise.setName("cmbViewEnterprise"); // NOI18N
        cmbViewEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViewEnterpriseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(networkJComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ComboBoxEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(60, 60, 60)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(156, 156, 156)
                                                        .addComponent(btnSubmit)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnDelete))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addComponent(cmbViewNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jLabel14)
                .addGap(41, 41, 41)
                .addComponent(cmbViewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(jLabel13)
                    .addComponent(btnDelete)
                    .addComponent(ComboBoxEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(cmbViewNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbViewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnterpriseMouseClicked
        // TODO add your handling code here:
        try {
            int table_selected_row;
            if (evt.getClickCount() == 2) {
                table_selected_row = tblEnterprise.getSelectedRow();
                viewOrganization = (Organization) tblEnterprise.getValueAt(table_selected_row, 0);
                
                viewNetwork = (Network) cmbViewNetwork.getSelectedItem();
                viewEnterprise = (Enterprise) cmbViewEnterprise.getSelectedItem();
                networkJComboBox.setSelectedItem(viewNetwork);
                ComboBoxEnterpriseType.setSelectedItem(viewEnterprise);
                
                
                txtName.setText(viewOrganization.getName());
                txtAddress1.setText(viewOrganization.getAddress1());
                txtAddress2.setText(viewOrganization.getAddress2());
                txtCity.setText(viewOrganization.getCity());
                txtState.setText(viewOrganization.getState());
                txtZip.setText(viewOrganization.getZip());
                txtPhone.setText(viewOrganization.getPhone());
                txtEmail1.setText(viewOrganization.getEmail());
                txtContactPerson.setText(viewOrganization.getContactPerson());
//                int enterpriseID = Integer.parseInt(tblEnterprise.getValueAt(table_selected_row, 0).toString());
                btnSubmit.setText("Update");
                btnDelete.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_tblEnterpriseMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
//         String regex = "^[A-Za-z0-9]+[A-Za-z0-9+_]+@[A-Za-z0-9.-]+$";
//        Pattern pattern = Pattern.compile(regex);
//        Matcher matcher = pattern.matcher(txtEmail1.getText());
//        if(txtEmail1.getText().equals("emailID with _ and @ only")) {
//            JOptionPane.showMessageDialog(null, "email id format is invalid");
//            return;
//        }
        String EnterpriseName = txtName.getText();
        String Address1 =txtAddress1.getText();
        String Address2 =txtAddress2.getText();
        String City =txtCity.getText();
        String State =txtState.getText();
        String Zip =txtZip.getText();
        String Phone =txtPhone.getText();
        String Email =txtEmail1.getText();
        String ContactPeroson =txtContactPerson.getText();
        

        if (!validateFields()) {
            return;
        }
            if (btnSubmit.getText().equals("Submit")) {
                addOrganization();
        } else {
            viewEnterprise.getOrganizationDirectory().getOrganizationList().remove(viewOrganization);
            addOrganization();
    
            btnSubmit.setText("Submit");
            btnDelete.setVisible(false);
        }
        
       

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null, "Delete Enterprise", "Are you sure you want to delete this enterprise?", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.OK_OPTION) {
            int table_selected_row = tblEnterprise.getSelectedRow();
            
            viewEnterprise.getOrganizationDirectory().getOrganizationList().remove(viewOrganization);
            dB4OUtil.storeSystem(system);
            JOptionPane.showMessageDialog(null, "Enterprise updated successfully");
            populateTable();
            clearFields();
            btnSubmit.setText("Submit");
            btnDelete.setVisible(false);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void cmbViewNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViewNetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network) cmbViewNetwork.getSelectedItem();
        if (network != null){
            populateViewEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_cmbViewNetworkActionPerformed

    private void cmbViewEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViewEnterpriseActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_cmbViewEnterpriseActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxEnterpriseType;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbViewEnterprise;
    private javax.swing.JComboBox cmbViewNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactPerson;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();
        model.setRowCount(0);
        Enterprise ent = (Enterprise) cmbViewEnterprise.getSelectedItem();
        if(ent == null) {
            return;
        }
        for(Organization org: ent.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[10];
                row[0] = org;
                row[1] = org.getAddress1();
                row[2] = org.getAddress2();
                row[3] = org.getCity();
                row[4] = org.getState();
                row[5] = org.getZip();
                row[6] = org.getPhone();
                row[7] = org.getEmail();
                row[8] = org.getContactPerson();
                row[9] = org.getName();
                model.addRow(row);
        }
    }
    
    private void addOrganization() {
        enterprise = (Enterprise) ComboBoxEnterpriseType.getSelectedItem();
                
                Type type;
                if(String.valueOf(enterprise.getName()).equals("Hospital Enterprise")) {
                    logger.debug("here1");
                    type = Organization.Type.Hospital;
                }
                else if(String.valueOf(enterprise.getName()).equals("Pharmacy Enterprise")) {
                    logger.debug("here2");
                    type = Organization.Type.Pharmacy;
                }
                else {
                    logger.debug("here3");
                    type = Organization.Type.Insurance;
                }
//                if (network == null || type == null) {
//                    JOptionPane.showMessageDialog(null, "Invalid Input!");
//                    return;
//                }
                String name = txtName.getText();
                String address1 = txtAddress1.getText();
                String address2 = txtAddress2.getText();
                String city = txtCity.getText();
                String state = txtState.getText();
                String zip = txtZip.getText();
                String phone = txtPhone.getText();
                String email = txtEmail1.getText();
                String contactPerson = txtContactPerson.getText();
//                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type, address1, address2,
//                        city, state, zip, phone, email, contactPerson);
                Organization org = enterprise.getOrganizationDirectory().createOrganization(type);
                org.setName(name);
                org.setAddress1(address1);
                org.setAddress2(address2);
                org.setCity(city);
                org.setState(state);
                org.setZip(zip);
                org.setPhone(phone);
                org.setEmail(email);
                org.setContactPerson(contactPerson);
                dB4OUtil.storeSystem(system);
                JOptionPane.showMessageDialog(null, "Enterprise added successfully");
                clearFields();
                populateTable();
    }
    private void populateViewComboBox() {
        cmbViewNetwork.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            cmbViewNetwork.addItem(network);
        }
       
    }

    private void populateViewEnterpriseComboBox(Network network) {
        cmbViewEnterprise.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            cmbViewEnterprise.addItem(enterprise);
        }
    }
    
    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        ComboBoxEnterpriseType.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            ComboBoxEnterpriseType.addItem(enterprise);
        }
        
    }
    
    private void populateComboBox() {
        ComboBoxEnterpriseType.removeAllItems();
        networkJComboBox.removeAllItems();
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            ComboBoxEnterpriseType.addItem(type);
        }

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

    public void clearFields() {
        txtName.setText("");
        txtAddress1.setText("");
        txtAddress2.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZip.setText("");
        txtPhone.setText("");
        txtEmail1.setText("");
        txtContactPerson.setText("");
        btnSubmit.setText("Add");
        btnDelete.setVisible(false);
    }
    
    public boolean validateFields(){
        String EnterpriseName = txtName.getText();
        String Address1 =txtAddress1.getText();
        String Address2 =txtAddress2.getText();
        String City =txtCity.getText();
        String State =txtState.getText();
        String Zip =txtZip.getText();
        String Phone =txtPhone.getText();
        String Email =txtEmail1.getText();
        String ContactPeroson =txtContactPerson.getText();
        if(EnterpriseName.trim().equals("") || ComboBoxEnterpriseType.getSelectedIndex()==-1 ||Address1.trim().equals("") ||
             Address2.trim().equals("") ||City.trim().equals("")|| 
            State.trim().equals("")||Zip.trim().equals("") ||
            Phone.trim().equals("") ||Email.trim().equals("")||
            ContactPeroson.trim().equals("") || networkJComboBox.getSelectedIndex()==-1) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

}
