/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telehealth;

import com.telehealth.Business.EcoSystem;
import javax.swing.JOptionPane;

/**
 *
 * @author bhaVYa
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    private EcoSystem system;
    public PatientPanel(TeleHealthView teleHealthView, EcoSystem system) {
        initComponents();
        comboPatientBloodGroup.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblPatientAddress1 = new javax.swing.JLabel();
        txtPatientAddress1 = new javax.swing.JTextField();
        lblPatientAddress2 = new javax.swing.JLabel();
        txtPatientAddress2 = new javax.swing.JTextField();
        lblPatientCity = new javax.swing.JLabel();
        txtPatientCity = new javax.swing.JTextField();
        lblPatientZipcode = new javax.swing.JLabel();
        lblPatientCountry = new javax.swing.JLabel();
        txtPatientCountry = new javax.swing.JTextField();
        lblPatientPhone = new javax.swing.JLabel();
        lblPatientEmail = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        comboPatientBloodGroup = new javax.swing.JComboBox<>();
        lblPatientBloodGroup = new javax.swing.JLabel();
        lblPatientDOB = new javax.swing.JLabel();
        txtPatientDOB = new javax.swing.JFormattedTextField();
        btnAddPatient = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDeletePatient = new javax.swing.JButton();
        txtPatientZipcode = new javax.swing.JFormattedTextField();
        txtPatientPhone = new javax.swing.JFormattedTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(telehealth.TeleHealthApp.class).getContext().getResourceMap(PatientPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtPatientName.setText(resourceMap.getString("txtPatientName.text")); // NOI18N
        txtPatientName.setName("txtPatientName"); // NOI18N

        lblPatientAddress1.setText(resourceMap.getString("lblPatientAddress1.text")); // NOI18N
        lblPatientAddress1.setName("lblPatientAddress1"); // NOI18N

        txtPatientAddress1.setName("txtPatientAddress1"); // NOI18N

        lblPatientAddress2.setText(resourceMap.getString("lblPatientAddress2.text")); // NOI18N
        lblPatientAddress2.setName("lblPatientAddress2"); // NOI18N

        txtPatientAddress2.setName("txtPatientAddress2"); // NOI18N

        lblPatientCity.setText(resourceMap.getString("lblPatientCity.text")); // NOI18N
        lblPatientCity.setName("lblPatientCity"); // NOI18N

        txtPatientCity.setName("txtPatientCity"); // NOI18N
        txtPatientCity.setPreferredSize(new java.awt.Dimension(10, 32));

        lblPatientZipcode.setText(resourceMap.getString("lblPatientZipcode.text")); // NOI18N
        lblPatientZipcode.setName("lblPatientZipcode"); // NOI18N

        lblPatientCountry.setText(resourceMap.getString("lblPatientCountry.text")); // NOI18N
        lblPatientCountry.setName("lblPatientCountry"); // NOI18N

        txtPatientCountry.setName("txtPatientCountry"); // NOI18N
        txtPatientCountry.setPreferredSize(new java.awt.Dimension(10, 32));

        lblPatientPhone.setText(resourceMap.getString("lblPatientPhone.text")); // NOI18N
        lblPatientPhone.setName("lblPatientPhone"); // NOI18N

        lblPatientEmail.setText(resourceMap.getString("lblPatientEmail.text")); // NOI18N
        lblPatientEmail.setName("lblPatientEmail"); // NOI18N

        txtPatientEmail.setName("txtPatientEmail"); // NOI18N
        txtPatientEmail.setPreferredSize(new java.awt.Dimension(10, 32));

        comboPatientBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "O-", "AB-", "B+", "A-" }));
        comboPatientBloodGroup.setMinimumSize(new java.awt.Dimension(82, 32));
        comboPatientBloodGroup.setName("comboPatientBloodGroup"); // NOI18N
        comboPatientBloodGroup.setPreferredSize(new java.awt.Dimension(82, 32));

        lblPatientBloodGroup.setText(resourceMap.getString("lblPatientBloodGroup.text")); // NOI18N
        lblPatientBloodGroup.setName("lblPatientBloodGroup"); // NOI18N

        lblPatientDOB.setText(resourceMap.getString("lblPatientDOB.text")); // NOI18N
        lblPatientDOB.setName("lblPatientDOB"); // NOI18N

        try {
            txtPatientDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPatientDOB.setMinimumSize(new java.awt.Dimension(10, 32));
        txtPatientDOB.setName("txtPatientDOB"); // NOI18N
        txtPatientDOB.setPreferredSize(new java.awt.Dimension(56, 32));

        btnAddPatient.setText(resourceMap.getString("btnAddPatient.text")); // NOI18N
        btnAddPatient.setName("btnAddPatient"); // NOI18N
        btnAddPatient.setPreferredSize(new java.awt.Dimension(116, 32));
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        btnReset.setText(resourceMap.getString("btnReset.text")); // NOI18N
        btnReset.setName("btnReset"); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(78, 32));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Date of Birth", "City", "Zipcode", "Country", "Phone No.", "Email ID", "Blood Group"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable2.columnModel.title0")); // NOI18N
            jTable2.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable2.columnModel.title1")); // NOI18N
            jTable2.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTable2.columnModel.title2")); // NOI18N
            jTable2.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTable2.columnModel.title3")); // NOI18N
            jTable2.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTable2.columnModel.title4")); // NOI18N
            jTable2.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("jTable2.columnModel.title5")); // NOI18N
            jTable2.getColumnModel().getColumn(6).setHeaderValue(resourceMap.getString("jTable2.columnModel.title6")); // NOI18N
            jTable2.getColumnModel().getColumn(7).setHeaderValue(resourceMap.getString("jTable2.columnModel.title7")); // NOI18N
        }

        btnDeletePatient.setText(resourceMap.getString("btnDeletePatient.text")); // NOI18N
        btnDeletePatient.setName("btnDeletePatient"); // NOI18N

        try {
            txtPatientZipcode.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPatientZipcode.setName("txtPatientZipcode"); // NOI18N
        txtPatientZipcode.setPreferredSize(new java.awt.Dimension(144, 32));

        try {
            txtPatientPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPatientPhone.setName("txtPatientPhone"); // NOI18N
        txtPatientPhone.setPreferredSize(new java.awt.Dimension(10, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPatientCity)
                        .addComponent(jLabel1)
                        .addComponent(lblPatientAddress1)
                        .addComponent(lblPatientCountry))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(txtPatientCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblPatientEmail)
                                    .addGap(50, 50, 50)
                                    .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPatientAddress1)
                                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPatientCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientDOB)
                                .addGap(50, 50, 50)
                                .addComponent(txtPatientDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeletePatient)
                                        .addGap(3, 3, 3)
                                        .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPatientBloodGroup)
                                            .addComponent(lblPatientZipcode)
                                            .addComponent(lblPatientAddress2)
                                            .addComponent(lblPatientPhone))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPatientAddress2)
                                                    .addComponent(txtPatientZipcode, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                                .addComponent(comboPatientBloodGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtPatientPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientDOB)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPatientAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPatientAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPatientAddress1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientAddress2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPatientZipcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPatientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientCity)
                        .addComponent(lblPatientZipcode)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientCountry)
                    .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientEmail)
                        .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientBloodGroup))
                    .addComponent(comboPatientBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        String patientName = txtPatientName.getText();
        String patientAddress1 = txtPatientAddress1.getText();
        String patientAddress2 = txtPatientAddress2.getText();
        String patientCity = txtPatientCity.getText();
        String patientZipcode = txtPatientZipcode.getText();
        String patientCountry = txtPatientCountry.getText();
        String patientPhone = txtPatientPhone.getText();
        String patientEmail = txtPatientEmail.getText();
        String patientDOB = txtPatientDOB.getText();
        String patientBloodGroup = comboPatientBloodGroup.getItemAt(comboPatientBloodGroup.getSelectedIndex());
        System.out.println("bg="+patientBloodGroup);
        
        if(patientName.equals("") || patientAddress1.equals("") || patientAddress2.equals("") || patientCity.equals("") || patientZipcode.equals("") ||
                patientCountry.equals("") || patientPhone.equals("(   )   -    ") || patientEmail.equals("") || patientDOB.equals("  /  /    ") || comboPatientBloodGroup.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Validation Error", "Please enter all the field", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnDeletePatient;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboPatientBloodGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblPatientAddress1;
    private javax.swing.JLabel lblPatientAddress2;
    private javax.swing.JLabel lblPatientBloodGroup;
    private javax.swing.JLabel lblPatientCity;
    private javax.swing.JLabel lblPatientCountry;
    private javax.swing.JLabel lblPatientDOB;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientZipcode;
    private javax.swing.JTextField txtPatientAddress1;
    private javax.swing.JTextField txtPatientAddress2;
    private javax.swing.JTextField txtPatientCity;
    private javax.swing.JTextField txtPatientCountry;
    private javax.swing.JFormattedTextField txtPatientDOB;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JFormattedTextField txtPatientPhone;
    private javax.swing.JFormattedTextField txtPatientZipcode;
    // End of variables declaration//GEN-END:variables
}
